---
# This role installs http

- name: Install http
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - apache2
   - php
   - php-mysql
   - git

- name: http service state
  service:
    name: apache2
    state: started
    enabled: yes