---
# This role installs redis
- name: Install redis
  apt:
    name: redis
    state: present

- name: Insert a line at the end of a file.
  lineinfile:
    path: "/etc/hosts"
    line: "127.0.0.1 redis"     