---
# This will install nagios

- name: Install Nagios4-common repository
  apt:
    deb: http://cz.archive.ubuntu.com/ubuntu/pool/universe/n/nagios4/nagios4-common_4.3.4-3_all.deb
    dpkg_options: 'force-confold,force-confdef'

- name: Install Nagios4-core repository
  apt:
    deb: http://cz.archive.ubuntu.com/ubuntu/pool/universe/n/nagios4/nagios4-core_4.3.4-3_amd64.deb
    dpkg_options: 'force-confold,force-confdef'

- name: Install Nagios-cgi repository
  apt:
    deb: http://cz.archive.ubuntu.com/ubuntu/pool/universe/n/nagios4/nagios4-cgi_4.3.4-3_amd64.deb
    dpkg_options: 'force-confold,force-confdef'

- name: Install Nagios repository
  apt:
    deb: http://cz.archive.ubuntu.com/ubuntu/pool/universe/n/nagios4/nagios4_4.3.4-3_amd64.deb
    dpkg_options: 'force-confold,force-confdef'

- name: install nagios
  apt: 
   pkg: "{{ item }}"
   state: present
   dpkg_options: 'force-confold,force-confdef'
  with_items:
   - nagios-nrpe-server
   - nagios-nrpe-plugin
   - nagios-plugins-standard
  notify: restart httpd

- name: create nagios config dir
  file: 
   path: "/etc/nagios4/ansible-managed"
   state: directory

- name: configure nagios
  copy: 
   src: "nagios.cfg"
   dest: "/etc/nagios4/nagios.cfg"
  notify: restart nagios

- name: configure localhost monitoring
  copy: 
   src: "localhost.cfg"
   dest: "/etc/nagios4/objects/localhost.cfg"
  notify: restart nagios

- name: configure nagios services
  copy: 
   src: "ansible-managed-services.cfg"
   dest: "/etc/nagios4/"

- name: create the nagios object files
  template: 
   src: "{{ item }}.j2"
   dest: "/etc/nagios4/ansible-managed/{{ item }}"
  with_items:
    - webservers.cfg
    - dbservers.cfg
    - lbservers.cfg
  notify: restart nagios

- name: Enable plugins for apache
  apache2_module:
   state: present
   name: "{{ item }}"
  with_items:
   - auth_digest
   - authz_groupfile

- name: start nagios
  service: 
   name: nagios4
   state: started
   enabled: yes