---
- name: Install http
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - python-pip

- name: Copy the code from repository
  git: 
   repo: "{{ repository }}"
   dest: "/var/www/html/code"

- name: Install specified python requirements.
  pip:
   requirements: "/var/www/html/code/requirements.txt"
 
- name: Insert a line at the end of a file.
  lineinfile:
    path: "/etc/hosts"
    line: "{{ hostvars[redis]['ansible_default_ipv4']['address'] }} redis" 