---
- name: Install http
  apt:
    name: ['python3-pip', 'libapache2-mod-wsgi-py3']
    state: present

- name: Copy the code from repository
  git: 
   repo: "{{ repository }}"
   dest: "/var/www/html/code"
   force: yes

- name: Install specified python requirements.
  pip:
   requirements: "/var/www/html/code/requirements.txt"
   executable: pip3

- name: Replace python file
  replace:
    dest: /var/www/html/code/app.py
    regexp: 'host="redis"'
    replace: host="{{ hostvars['redis']['ansible_default_ipv4']['address'] }}"

- name: Copy virtualhost config
  template: 
   src: "000-default.conf.j2"
   dest: "/etc/apache2/sites-available/000-default.conf"

- name: reload apache
  service:
   name: apache2
   state: restarted