---
- name: Install http
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - python3-pip

- name: Copy the code from repository
  git: 
   repo: "{{ repository }}"
   dest: "/var/www/html/code"
   force: yes

- name: Install specified python requirements.
  pip:
   requirements: "/var/www/html/code/requirements.txt"
   executable: pip-3
 
- name: Insert a line at the end of a file.
  lineinfile:
   path: "/etc/hosts"
   line: "{{ hostvars['redis']['ansible_default_ipv4']['address'] }} redis"

- name: Enable CGI
  apache2_module:
   state: present
   name: cgi

- name: reload apache
  service:
   name: apache2
   state: restarted